sources:
  simple-krr-dashboard:
    kind: dockerimage
    spec:
      image: devopsiaci/simple-krr-dashboard
      architecture: linux/amd64
      versionfilter:
        kind: semver
  krr:
    kind: dockerimage
    spec:
      image: robustadev/krr
      architecture: linux/amd64
      versionfilter:
        kind: semver
conditions: {}
targets:
  simple-krr-dashboard-helm:
    name: bump simple-krr-dashboard helm chart
    kind: helmchart
    spec:
      name: charts/simple-krr-dashboard
      file: Chart.yaml
      key: $.appVersion
      versionincrement: none
    sourceid: simple-krr-dashboard
  simple-krr-helm:
    name: bump simple-krr-dashboard helm chart
    kind: helmchart
    spec:
      name: charts/simple-krr-dashboard
      file: values.yaml
      key: $.job.image.tag
      versionincrement: none
    sourceid: krr
